In [3]:
%pip install -qU pandas tqdm

from tqdm import tqdm

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Utils

In [9]:
%pip install -q newspaper3k lxml

from newspaper import Article


def fetch_one_article(url: str) -> str | None:
    try:
        article = Article(url)
        article.download()
        article.parse()
        return article.text
    except Exception as e:
        print(f"Error fetching {url}: {str(e)}")
        return None

[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

In [5]:
from urllib.parse import urlparse


def get_domain(url):
    return urlparse(url).netloc.split("www.")[-1]

### Load not fetchable domains

Domains that we know can't be fetched using newspaper3k because of restrictions

In [8]:
NOT_FETCHABLE_DOMAINS = open("not_fechable_domains.txt").read().splitlines()

NOT_FETCHABLE_DOMAINS[:3]

['skift.com', '247wallst.com', 'windowsreport.com']

# Update MongoDB with article contents

In [2]:
from dotenv import load_dotenv
from pymongo import MongoClient
import os

load_dotenv()

client = MongoClient(os.getenv("MONGODB_URI"))

db = client["blogdb"]

collection = db["ai_news"]

### Add a domain field

In [6]:
from pymongo import UpdateOne

# Batch size for processing
BATCH_SIZE = 1000

# Find all documents without a domain field
docs_without_domain = collection.find(
    {"domain": {"$exists": False}}, {"_id": 1, "url": 1}
)

# Count total documents to update for the progress bar
total_docs = collection.count_documents({"domain": {"$exists": False}})

updated_count = 0
bulk_operations = []

# Process documents in batches
for doc in tqdm(docs_without_domain, total=total_docs, desc="Processing documents"):
    if "url" in doc:
        domain = get_domain(doc["url"])
        bulk_operations.append(
            UpdateOne({"_id": doc["_id"]}, {"$set": {"domain": domain}})
        )

    # If we've reached the batch size, execute the bulk operation
    if len(bulk_operations) >= BATCH_SIZE:
        result = collection.bulk_write(bulk_operations)
        updated_count += result.modified_count
        bulk_operations = []

# Execute any remaining operations
if bulk_operations:
    result = collection.bulk_write(bulk_operations)
    updated_count += result.modified_count

print(f"Added domain to {updated_count} documents")

# Verify that all documents now have a domain
remaining_docs = collection.count_documents({"domain": {"$exists": False}})
assert (
    remaining_docs == 0
), f"There are still {remaining_docs} documents without a domain"

Processing documents: 100%|██████████| 26106/26106 [01:30<00:00, 289.35it/s]

Added domain to 26106 documents

In [ ]:
import time
import random
from tqdm import tqdm
from collections import defaultdict


def process_articles():
    # Query for documents without page_content and with fetchable domains
    query = {
        "page_content": {"$exists": False},
        "domain": {"$nin": NOT_FETCHABLE_DOMAINS},
    }

    projection = {"_id": 1, "url": 1}

    # Get total count for progress bar
    total_docs = collection.count_documents(query)

    previous_domain = None
    domain_errors = defaultdict(int)
    ignored_domains = set()

    for doc in tqdm(
        collection.find(query, projection), total=total_docs, desc="Processing articles"
    ):
        url = doc["url"]
        current_domain = get_domain(url)

        # Skip if domain is in ignored list
        if current_domain in ignored_domains:
            print(f"Skipping {url} (domain ignored due to multiple failures)")
            continue

        # If the domain is the same as the previous request, add a delay
        if current_domain == previous_domain:
            time.sleep(random.uniform(0.5, 2))

        content = fetch_one_article(url)

        if content:
            result = collection.update_one(
                {"_id": doc["_id"]}, {"$set": {"page_content": content}}
            )
            print(f"Updated {url}")
            # Reset error count for successful fetch
            domain_errors[current_domain] = 0
        else:
            print(f"No content fetched for {url}")
            domain_errors[current_domain] += 1

            # Check if domain should be ignored
            if domain_errors[current_domain] >= 3:
                ignored_domains.add(current_domain)
                print(f"Domain {current_domain} added to ignored list after 3 failures")

        previous_domain = current_domain

    print(f"Domains ignored due to multiple failures: {ignored_domains}")
    return ignored_domains


# Main execution
try:
    newly_ignored_domains = process_articles()

    # Optionally, update NOT_FETCHABLE_DOMAINS with newly ignored domains
    NOT_FETCHABLE_DOMAINS.extend(newly_ignored_domains)
    print(f"Updated NOT_FETCHABLE_DOMAINS: {NOT_FETCHABLE_DOMAINS}")

except KeyboardInterrupt:
    print("Process interrupted by user. Progress saved.")

# Update a CSV file

In [ ]:
%pip install -q pandas

import pandas as pd

### Load data from CSV

In [38]:
FILE = r"data\blogdb.ai_news_2024_07_02_no_embedding.csv"

df = pd.read_csv(FILE)

df.head()

,_id,date,title,body,url,image,source,found_at,page_content
0,667d1ef6fc45eb48396a6a0c,2024-06-20T14:00:00.000Z,Anthropic's rivalry with OpenAI heats up with ...,Just a month after OpenAI rolled out its lates...,https://www.msn.com/en-us/news/technology/anth...,https://img-s-msn-com.akamaized.net/tenant/amp...,Fortune on MSN.com,2024-06-26T09:51:56.553Z,NaN
1,667d1ef6fc45eb48396a6a07,2024-06-25T12:00:00.000Z,Etched is building an AI chip that only runs o...,"The transformer, proposed by a team of Google ...",https://techcrunch.com/2024/06/25/etched-is-bu...,https://techcrunch.com/wp-content/uploads/2023...,TechCrunch,2024-06-26T09:51:56.553Z,As generative AI touches a growing number of i...
2,667d1ef6fc45eb48396a6a06,2024-06-25T21:49:00.000Z,Boston scientists create AI model to 'catch Al...,Researchers say they've created a promising AI...,https://www.msn.com/en-us/health/other/boston-...,https://img-s-msn-com.akamaized.net/tenant/amp...,Tribune News Service on MSN.com,2024-06-26T09:51:56.553Z,NaN
3,667d1ef6fc45eb48396a6a0f,2024-06-25T18:07:00.000Z,FDA clears new AI-powered 12-lead ECG from Ali...,AliveCor announced today that it received FDA ...,https://www.massdevice.com/fda-clears-ai-12-le...,https://www.massdevice.com/wp-content/uploads/...,MassDevice,2024-06-26T09:51:56.553Z,AliveCor announced today that it received FDA ...
4,667d1ef6fc45eb48396a6a11,2024-06-26T08:00:00.000Z,EasyTranslate thinks augmenting LLMs with huma...,But now it's headed in a new direction with a ...,https://techcrunch.com/2024/06/26/easytranslat...,NaN,TechCrunch,2024-06-26T09:51:56.553Z,You might think new generative AI startups lik...

### Add `domain` field

In [39]:
df["domain"] = df["url"].apply(get_domain)

df.head()

,_id,date,title,body,url,image,source,found_at,page_content,domain
0,667d1ef6fc45eb48396a6a0c,2024-06-20T14:00:00.000Z,Anthropic's rivalry with OpenAI heats up with ...,Just a month after OpenAI rolled out its lates...,https://www.msn.com/en-us/news/technology/anth...,https://img-s-msn-com.akamaized.net/tenant/amp...,Fortune on MSN.com,2024-06-26T09:51:56.553Z,NaN,msn.com
1,667d1ef6fc45eb48396a6a07,2024-06-25T12:00:00.000Z,Etched is building an AI chip that only runs o...,"The transformer, proposed by a team of Google ...",https://techcrunch.com/2024/06/25/etched-is-bu...,https://techcrunch.com/wp-content/uploads/2023...,TechCrunch,2024-06-26T09:51:56.553Z,As generative AI touches a growing number of i...,techcrunch.com
2,667d1ef6fc45eb48396a6a06,2024-06-25T21:49:00.000Z,Boston scientists create AI model to 'catch Al...,Researchers say they've created a promising AI...,https://www.msn.com/en-us/health/other/boston-...,https://img-s-msn-com.akamaized.net/tenant/amp...,Tribune News Service on MSN.com,2024-06-26T09:51:56.553Z,NaN,msn.com
3,667d1ef6fc45eb48396a6a0f,2024-06-25T18:07:00.000Z,FDA clears new AI-powered 12-lead ECG from Ali...,AliveCor announced today that it received FDA ...,https://www.massdevice.com/fda-clears-ai-12-le...,https://www.massdevice.com/wp-content/uploads/...,MassDevice,2024-06-26T09:51:56.553Z,AliveCor announced today that it received FDA ...,massdevice.com
4,667d1ef6fc45eb48396a6a11,2024-06-26T08:00:00.000Z,EasyTranslate thinks augmenting LLMs with huma...,But now it's headed in a new direction with a ...,https://techcrunch.com/2024/06/26/easytranslat...,NaN,TechCrunch,2024-06-26T09:51:56.553Z,You might think new generative AI startups lik...,techcrunch.com

# Find not featchable domains

In [40]:
domain_popularity = df["domain"].value_counts()

domain_popularity.head(10)

domain
msn.com                        6851
finance.yahoo.com               867
yahoo.com                       667
forbes.com                      589
linkedin.com                    398
markets.businessinsider.com     369
tmcnet.com                      330
techcrunch.com                  233
businessinsider.com             213
lelezard.com                    192
Name: count, dtype: int64

In [41]:
one_article_per_domain = (
    df.sort_values("date", ascending=False)
    .drop_duplicates(subset="domain")
    .assign(domain_popularity=lambda x: x["domain"].map(domain_popularity))
    .sort_values("domain_popularity", ascending=False)
    .reset_index(drop=True)
)

one_article_per_domain.head(5)

,_id,date,title,body,url,image,source,found_at,page_content,domain,domain_popularity
0,6683b1f393fb337940318a80,2024-07-02T07:36:00.000Z,"OpenAI introduces CriticGPT, a GPT 4-based mod...","OpenAI has recently unveiled CriticGPT, which ...",https://www.msn.com/en-in/money/news/openai-in...,https://images.moneycontrol.com/static-mcnews/...,moneycontrol.com on MSN.com,2024-07-02T07:39:30.786Z,NaN,msn.com,6851
1,6683b1f393fb33794031890d,2024-07-02T07:29:00.000Z,(XS2491029380.SG),As the AI race continues to spearhead the tech...,https://finance.yahoo.com/quote/XS2491029380.S...,NaN,Yahoo Finance,2024-07-02T07:39:05.217Z,NaN,finance.yahoo.com,867
2,6683b1f393fb337940318ab8,2024-07-02T05:27:00.000Z,L.A. Metro safety concerns amid back-to-back s...,"In a span of just six and half hours, two Los ...",https://www.yahoo.com/news/l-metro-safety-conc...,https://s.yimg.com/ny/api/res/1.2/WsqLx4.5VqB3...,Yahoo,2024-07-02T07:39:35.204Z,NaN,yahoo.com,667
3,6683b1f393fb3379403189c5,2024-07-02T02:55:00.000Z,W San Francisco Partners With SIA Scotch Whisk...,"The W San Francisco hosted the annual ""What Sh...",https://www.forbes.com/sites/noelburgess/2024/...,https://imageio.forbes.com/specials-images/ima...,Forbes,2024-07-02T07:39:17.900Z,NaN,forbes.com,589
4,6683b1f393fb33794031925e,2024-07-02T00:31:00.000Z,Big tech eyes nuclear power for AI,The artificial intelligence boom has tech comp...,https://www.linkedin.com/news/story/big-tech-e...,https://media.licdn.com/dms/image/D4E1AAQFTU1I...,LinkedIn,2024-07-02T07:44:06.967Z,NaN,linkedin.com,398

### Fetch the articles content for the top domains to check if fetching works

In [42]:
from langchain_community.document_loaders import NewsURLLoader

TOP_K = 500

print(f"Will fetch one article for each of the top {TOP_K} domains")

urls = one_article_per_domain["url"].tolist()[:TOP_K]

loader = NewsURLLoader(urls, show_progress_bar=True, continue_on_failure=True)

data = []
# data = loader.load()

Will fetch one article for each of the top 500 domains

In [43]:
for doc in [doc for doc in data if doc.page_content][:10]:
    print(f"Title: {doc.metadata['title']}")
    print(f"URL: {doc.metadata['link']}")
    print(f"Text: {doc.page_content}...")  # Print first 100 characters
    print("---")
    print()

In [44]:
empty_page_content = [x.metadata["link"] for x in data if not x.page_content]

empty_page_content

[]

In [45]:
# failed_urls = list(
#     set(urls) - set(x.metadata["link"] for x in data) | set(empty_page_content)
# )
# failed_domains = [get_domain(url) for url in failed_urls]

# failed_domains[:10]

In [46]:
failed_domains = {
    "skift.com",
    "247wallst.com",
    "windowsreport.com",
    "news-medical.net",
    "heise.de",
    "news18.com",
    "khaleejtimes.com",
    "venturebeat.com",
    "dbta.com",
    "autoevolution.com",
    "finbold.com",
    "techstory.in",
    "ca.finance.yahoo.com",
    "hollywoodreporter.com",
    "pc-tablet.com",
    "cmswire.com",
    "bbc.co.uk",
    "barrons.com",
    "marktechpost.com",
    "bbc.com",
    "businesstoday.in",
    "bgr.com",
    "wfmz.com",
    "geeky-gadgets.com",
    "mobileworldlive.com",
    "latimes.com",
    "philstar.com",
    "9to5mac.com",
    "cio.economictimes.indiatimes.com",
    "dqindia.com",
    "law.com",
    "androidauthority.com",
    "telecoms.com",
    "variety.com",
    "securityboulevard.com",
    "securitysystemsnews.com",
    "uk.pcmag.com",
    "morningstar.com",
    "bworldonline.com",
    "windowscentral.com",
    "djournal.com",
    "marketplace.org",
    "thefastmode.com",
    "baltimoresun.com",
    "crn.com",
    "punchng.com",
    "foxbusiness.com",
    "indiaeducationdiary.in",
    "usnews.com",
    "infoworld.com",
    "theconversation.com",
    "moneycontrol.com",
    "indianexpress.com",
    "microsoft.com",
    "arabianbusiness.com",
    "finanznachrichten.de",
    "news.yahoo.com",
    "livemint.com",
    "yourstory.com",
    "onrec.com",
    "inc42.com",
    "financialit.net",
    "techopedia.com",
    "tech-critter.com",
    "fxstreet.com",
    "computerworld.com",
    "mybroadband.co.za",
    "crowdfundinsider.com",
    "uk.news.yahoo.com",
    "abc.net.au",
    "infoq.com",
    "fiercehealthcare.com",
    "bloomberg.com",
    "benzinga.com",
    "telegraph.co.uk",
    "eagletribune.com",
    "futurism.com",
    "menafn.com",
    "adage.com",
    "semiengineering.com",
    "artificiallawyer.com",
    "wired.com",
    "tweaktown.com",
    "campustechnology.com",
    "sports.yahoo.com",
    "neowin.net",
    "hbr.org",
    "insidebigdata.com",
    "bernama.com",
    "medianama.com",
    "financialpost.com",
    "twinfinite.net",
    "yicaiglobal.com",
    "thehindu.com",
    "rcrwireless.com",
    "computerweekly.com",
    "executivegov.com",
    "businesstimes.com.sg",
    "cnet.com",
    "ciodive.com",
    "es-us.finanzas.yahoo.com",
    "pcmag.com",
    "phonearena.com",
    "pbs.org",
    "gizchina.com",
    "statnews.com",
    "businessghana.com",
    "global.chinadaily.com.cn",
    "businessinsider.in",
    "gizmodo.com",
    "pocket-lint.com",
    "sciencedaily.com",
    "csoonline.com",
    "straitstimes.com",
    "theedgesingapore.com",
    "news.crunchbase.com",
    "knowyourmeme.com",
    "decrypt.co",
    "enterprisetimes.co.uk",
    "news.europawire.eu",
    "kelo.com",
    "pcgamesn.com",
    "manilatimes.net",
    "thederrick.com",
    "itweb.co.za",
    "marketing-interactive.com",
    "nextgov.com",
    "fortune.com",
    "technode.com",
    "techradar.com",
    "livescience.com",
    "edition.cnn.com",
    "theregister.com",
    "tomsguide.com",
    "hackernoon.com",
    "valdostadailytimes.com",
    "ctvnews.ca",
    "businessinsider.com",
    "techspot.com",
    "sg.finance.yahoo.com",
    "thesangaiexpress.com",
    "telegraphindia.com",
    "euronews.com",
    "mirror.co.uk",
    "gulf-times.com",
    "au.pcmag.com",
    "lomeactu.com",
    "economictimes.indiatimes.com",
    "finance.yahoo.com",
    "federalnewsnetwork.com",
    "br.advfn.com",
    "deccanchronicle.com",
    "siliconindia.com",
    "ca.news.yahoo.com",
    "aibusiness.com",
    "scientificamerican.com",
    "ntnews.com.au",
    "eurekalert.org",
    "musicbusinessworldwide.com",
    "businessmirror.com.ph",
    "coingape.com",
    "sharecafe.com.au",
    "economist.com",
    "ign.com",
    "timesunion.com",
    "livebitcoinnews.com",
    "washingtonpost.com",
    "foxnews.com",
    "ippmedia.com",
    "hrdive.com",
    "pressdemocrat.com",
    "rediff.com",
    "beebom.com",
    "thurrott.com",
    "thewindowsclub.com",
    "informazione.it",
    "poynter.org",
    "searchengineland.com",
    "indiatoday.in",
    "eschoolnews.com",
    "digitaljournal.com",
    "stockhouse.com",
    "bleedingcool.com",
    "androguider.com",
    "infosecurity-magazine.com",
    "scmagazine.com",
    "odishatv.in",
    "livewiremarkets.com",
    "securityinfowatch.com",
    "cio.com",
    "pcworld.com",
    "au.finance.yahoo.com",
    "redmondmag.com",
    "cbc.ca",
    "insidebitcoins.com",
    "nbclosangeles.com",
    "fool.com",
    "wsj.com",
    "billboard.com",
    "sg.news.yahoo.com",
    "neurosciencenews.com",
    "sharewise.com",
    "ibtimes.com",
    "forbes.com",
    "nextbigfuture.com",
    "news.webindia123.com",
    "unite.ai",
    "energycentral.com",
    "nzherald.co.nz",
    "newsbytesapp.com",
    "digitaltrends.com",
    "thisdaylive.com",
    "mensjournal.com",
    "beincrypto.com",
    "news.sky.com",
    "breakingdefense.com",
    "tradearabia.com",
    "thenextweb.com",
    "destinationcrm.com",
    "genengnews.com",
    "therobotreport.com",
    "mumbrella.com.au",
    "hoodline.com",
    "techcrunch.com",
    "kahawatungu.com",
    "nasdaq.com",
    "gigazine.net",
    "itnews.com.au",
    "apnews.com",
    "techrepublic.com",
    "sdtimes.com",
    "iblnews.org",
    "investopedia.com",
    "cbsnews.com",
    "technical.ly",
    "seekingalpha.com",
    "inverse.com",
    "geekwire.com",
    "leewayhertz.com",
    "diginomica.com",
    "fmiblog.com",
    "itwire.com",
    "outlookindia.com",
    "cybernews.com",
    "hindustantimes.com",
    "koreaherald.com",
    "aastocks.com",
    "finextra.com",
    "thehackernews.com",
    "techrights.org",
    "techxplore.com",
    "victoriaadvocate.com",
    "slator.com",
    "dallasinnovates.com",
    "saipantribune.com",
    "miamiherald.com",
    "cnn.com",
    "timesofindia.indiatimes.com",
    "komando.com",
    "cyprus-mail.com",
    "travelweekly.com.au",
    "gizmodo.com.au",
    "lablab.ai",
    "datacenterdynamics.com",
    "observer.com",
    "digit.in",
    "firstpost.com",
    "prnewswire.co.uk",
    "devdiscourse.com",
    "animenewsnetwork.com",
    "darkreading.com",
    "arstechnica.com",
    "ft.com",
    "sourcesecurity.com",
    "frontiersin.org",
    "guru3d.com",
    "coinspeaker.com",
    "thewrap.com",
    "telecom.economictimes.indiatimes.com",
    "bangkokpost.com",
    "channelnewsasia.com",
    "news.bloomberglaw.com",
    "technology.inquirer.net",
    "deadline.com",
    "htxt.co.za",
    "joplinglobe.com",
    "thedrum.com",
    "scoop.co.nz",
    "fastcompany.com",
    "technologynetworks.com",
    "newscientist.com",
    "en.globes.co.il",
    "thehill.com",
    "filmibeat.com",
    "time.com",
    "mobilemarketingmagazine.com",
    "medscape.com",
    "infotechlead.com",
    "biometricupdate.com",
    "theatlantic.com",
    "thehindubusinessline.com",
    "hackaday.com",
    "theprint.in",
    "eurogamer.net",
    "businesswire.com",
    "money.rediff.com",
    "indiatvnews.com",
    "cacm.acm.org",
    "ndtv.com",
    "it-online.co.za",
    "news.marketersmedia.com",
    "asia.nikkei.com",
    "tvbeurope.com",
    "govtech.com",
    "jpost.com",
    "daytondailynews.com",
    "vietbao.vn",
    "linkedin.com",
    "technologyreview.com",
    "dailytelegraph.com.au",
    "cryptobriefing.com",
    "advanced-television.com",
    "pocketgamer.com",
    "cryptopolitan.com",
    "gamespot.com",
    "ibtimes.co.uk",
    "visualstudiomagazine.com",
    "cnbctv18.com",
    "vir.com.vn",
    "nypost.com",
    "entrepreneur.com",
    "freepressjournal.in",
    "thenews-chronicle.com",
    "theglobeandmail.com",
    "gizbot.com",
    "news.microsoft.com",
    "singularityhub.com",
    "networkworld.com",
    "techbullion.com",
    "thestar.com.my",
    "electronicdesign.com",
    "cambridge.org",
    "ocbj.com",
    "beckershospitalreview.com",
    "gadgets360.com",
    "smh.com.au",
    "popsci.com",
    "electronics360.globalspec.com",
    "nbcnews.com",
    "markets.businessinsider.com",
    "nytimes.com",
    "techzine.eu",
    "albawaba.com",
    "asiaone.com",
    "financialexpress.com",
    "chicagotribune.com",
    "thejournal.com",
    "theinformation.com",
    "campaignasia.com",
    "uk.investing.com",
    "siliconrepublic.com",
    "insidehpc.com",
    "designnews.com",
    "daijiworld.com",
    "au.news.yahoo.com",
    "insidermonkey.com",
    "in.mashable.com",
    "thehansindia.com",
    "chinadaily.com.cn",
    "fudzilla.com",
    "scitechdaily.com",
    "bignewsnetwork.com",
    "irishtimes.com",
    "brandequity.economictimes.indiatimes.com",
    "phys.org",
    "tradersmagazine.com",
    "goshennews.com",
    "analyticsindiamag.com",
    "appleinsider.com",
    "gazette.com",
    "hcamag.com",
    "adexchanger.com",
    "aboutamazon.com",
    "thesun.co.uk",
    "9to5google.com",
    "digitimes.com",
    "news.com.au",
    "business-standard.com",
    "nbcnewyork.com",
    "uk.finance.yahoo.com",
    "fbcnews.com.fj",
    "edweek.org",
    "crypto-news-flash.com",
    "deccanherald.com",
    "tmcnet.com",
    "china.org.cn",
    "politico.com",
    "newswit.com",
    "gulfnews.com",
    "dexerto.com",
    "vox.com",
    "dailydot.com",
    "lifehacker.com",
    "bizjournals.com",
    "lelezard.com",
    "dailymail.co.uk",
    "androidpolice.com",
    "medindia.net",
    "dailyhodl.com",
    "cryptonews.com",
    "dcvelocity.com",
    "searchenginejournal.com",
    "buffalo.edu",
    "macrumors.com",
    "cointelegraph.com",
    "inc.com",
    "jdsupra.com",
    "gamerant.com",
    "mmm-online.com",
    "fiverr.com",
    "newsweek.com",
    "pionline.com",
    "syncedreview.com",
    "mg.co.za",
    "psychologytoday.com",
    "crn.com.au",
    "stuff.tv",
    "couriermail.com.au",
    "tribune.com.pk",
    "scmp.com",
    "globaltimes.cn",
    "androidheadlines.com",
    "nocamels.com",
    "playtoearngames.com",
    "theverge.com",
    "english.aawsat.com",
    "malaysiasun.com",
    "techreport.com",
    "newatlas.com",
    "hothardware.com",
    "bleepingcomputer.com",
    "tbsnews.net",
    "sdxcentral.com",
    "investing.com",
    "independent.co.uk",
    "bbntimes.com",
    "msn.com",
    "tribuneindia.com",
    "abcnews.go.com",
    "securityweek.com",
    "newindianexpress.com",
    "design-reuse.com",
    "techtimes.com",
    "marketwatch.com",
    "bandt.com.au",
    "taiwannews.com.tw",
    "gizmochina.com",
    "rappler.com",
    "channelnews.com.au",
    "zawya.com",
    "washingtontimes.com",
    "fonearena.com",
    "fedscoop.com",
    "dailymemphian.com",
    "news.stocktradersdaily.com",
    "betakit.com",
    "yahoo.com",
    "themalaysianreserve.com",
    "zdnet.com",
    "afr.com",
    "israel21c.org",
    "siliconangle.com",
    "datanami.com",
    "seattletimes.com",
    "digitalinformationworld.com",
    "koreatimes.co.kr",
    "standard.co.uk",
    "sfgate.com",
    "tech.hindustantimes.com",
    "accountingtoday.com",
    "americanbanker.com",
    "econotimes.com",
    "bostonglobe.com",
    "01net.it",
    "money.usnews.com",
    "nature.com",
    "thestreet.com",
    "campaignlive.co.uk",
    "medicalxpress.com",
    "zeebiz.com",
    "mashable.com",
    "taipeitimes.com",
    "usatoday.com",
    "manilastandard.net",
    "defenseone.com",
    "insidehighered.com",
    "wgnradio.com",
    "smartcompany.com.au",
    "theaustralian.com.au",
    "reuters.com",
}

In [47]:
for doc in [doc for doc in data if doc.page_content][:2]:
    print(f"Title: {doc.metadata['title']}")
    print(f"URL: {doc.metadata['link']}")
    print(f"Text: {doc.page_content}...")  # Print first 100 characters
    print("---")
    print()

# Fetch the missing articles using `newspaper3k`

In [51]:
import time
import random
from newspaper import Article
from tqdm import tqdm
import pandas as pd
from collections import defaultdict


def process_articles(
    df, limit: int | None = None, failed_domains: set[str] | None = None, max_failures=3
):
    """
    Process articles from a DataFrame, fetching content for each article URL.

    This function iterates through the provided DataFrame, attempting to fetch
    the content for each article URL. It respects rate limiting, skips articles
    from failed domains, stops processing after reaching the specified limit,
    and tracks new domains that consistently fail.

    Parameters:
    -----------
    df : pandas.DataFrame
        A DataFrame containing article information. Must include 'url' and
        'page_content' columns.
    limit : int, optional
        The maximum number of articles to process. If None, all articles are processed.
    failed_domains : set, optional
        A set of domain names to skip (e.g., {'example.com', 'faildomain.com'}).
    max_failures : int, optional
        The number of failures allowed for a domain before it's added to ignored_domains.

    Returns:
    --------
    tuple
        A tuple containing:
        - The updated DataFrame with fetched content in the 'page_content' column.
        - A set of newly ignored domains.

    Side Effects:
    -------------
    - Updates the input DataFrame in-place.
    """
    failed_domains = failed_domains or set()
    new_failed_domains = set()
    domain_failures = defaultdict(int)

    previous_domain = None
    updated_count = 0
    skipped_count = 0
    processed_count = 0

    for _, row in tqdm(df.iterrows(), total=len(df), desc="Processing articles"):
        if limit is not None and processed_count >= limit:
            print(f"Reached the limit of {limit} articles. Stopping.")
            break

        url = row["url"]
        current_domain = get_domain(url)

        # Skip if the domain is in the failed_domains or ignored_domains list
        if current_domain in failed_domains or current_domain in new_failed_domains:
            # print(f"Skipping {url} (domain failing)")
            skipped_count += 1
            continue

        # Skip if content already exists
        if pd.notna(row["page_content"]):
            # print(f"Content already exists for {url}")
            skipped_count += 1
            continue

        # If the domain is the same as the previous request, add a delay
        if current_domain == previous_domain:
            time.sleep(random.uniform(1, 3))

        content = fetch_one_article(url)

        if content:
            # Update the DataFrame
            df.at[_, "page_content"] = content
            print(f"Updated content for {url}")
            updated_count += 1
            # Reset failure count for successful fetch
            domain_failures[current_domain] = 0
        else:
            print(f"No content fetched for {url}")
            skipped_count += 1
            # Increment failure count for the domain
            domain_failures[current_domain] += 1

            # Check if domain should be ignored
            if domain_failures[current_domain] >= max_failures:
                new_failed_domains.add(current_domain)
                print(
                    f"Added {current_domain} to ignored domains after {max_failures} failures"
                )

        previous_domain = current_domain
        processed_count += 1

    print(f"Updated {updated_count} articles, skipped {skipped_count} articles")
    print(f"Total processed: {processed_count}")
    print(f"Newly ignored domains: {new_failed_domains}")
    return df, new_failed_domains


# Example usage
try:
    df, new_ignored_domains = process_articles(
        df, limit=None, failed_domains=set(failed_domains)
    )

    # Update failed_domains with newly ignored domains
    failed_domains.update(new_ignored_domains)

except KeyboardInterrupt:
    print("Process interrupted by user. Progress saved.")

Processing articles:  97%|█████████▋| 25451/26106 [1:07:15<06:03,  1.80it/s]

Updated content for https://ecommercefastlane.com/how-to-create-a-digital-marketing-package/

Processing articles:  98%|█████████▊| 25465/26106 [1:07:16<02:24,  4.44it/s]

Updated content for https://kval.com/news/local/wildfire-season-prepare-protect-kval-preparing-you-for-the-upcoming-wildfire-season

Processing articles:  98%|█████████▊| 25471/26106 [1:07:17<02:24,  4.41it/s]

Updated content for https://www.businessofapps.com/app-leaders/taras-kiseliuk/

Processing articles:  98%|█████████▊| 25476/26106 [1:07:18<02:13,  4.72it/s]

Updated content for https://sciencebusiness.net/network-updates/attract-pre-final-conference-discover-funded-projects

Processing articles:  98%|█████████▊| 25480/26106 [1:07:18<02:01,  5.16it/s]

Updated content for https://www.videogamer.com/news/i-hope-banana-doesnt-make-more-of-these-worthless-games-blow-up-on-steam/

Processing articles:  98%|█████████▊| 25482/26106 [1:07:19<02:14,  4.62it/s]

Error fetching https://www.thedailystar.com/news/national/imyfone-magicmic-the-best-ai-voice-changer-for-pc-and-mobile/article_f3b6c154-b5a2-5992-abeb-5425a273f24a.html: Article `download()` failed with 451 Client Error: Unavailable For Legal Reasons for url: https://www.thedailystar.com/news/national/imyfone-magicmic-the-best-ai-voice-changer-for-pc-and-mobile/article_f3b6c154-b5a2-5992-abeb-5425a273f24a.html on URL https://www.thedailystar.com/news/national/imyfone-magicmic-the-best-ai-voice-changer-for-pc-and-mobile/article_f3b6c154-b5a2-5992-abeb-5425a273f24a.html
No content fetched for https://www.thedailystar.com/news/national/imyfone-magicmic-the-best-ai-voice-changer-for-pc-and-mobile/article_f3b6c154-b5a2-5992-abeb-5425a273f24a.html
Added thedailystar.com to ignored domains after 3 failures

Processing articles:  98%|█████████▊| 25495/26106 [1:07:20<01:19,  7.67it/s]

Updated content for https://www.tabletopgamingnews.com/let-the-games-begin-brings-50-mini-games-and-challenges-to-dd-5e-campaigns/

Processing articles:  98%|█████████▊| 25498/26106 [1:07:21<01:28,  6.88it/s]

Updated content for https://www.rollingstone.com/culture-council/articles/top-5-trends-sports-tech-2024-1235049632/

Processing articles:  98%|█████████▊| 25506/26106 [1:07:21<01:12,  8.29it/s]

Updated content for https://www.columbian.com/news/2024/jul/01/as-ai-gains-a-workplace-foothold-states-are-trying-to-make-sure-workers-dont-get-left-behind/

Processing articles:  98%|█████████▊| 25511/26106 [1:07:22<01:16,  7.77it/s]

Updated content for https://hrexecutive.com/next-gen-hr-solutions-integrating-ai-for-competitive-advantage/

Processing articles:  98%|█████████▊| 25517/26106 [1:07:23<01:21,  7.26it/s]

Updated content for https://wjon.com/scsu-team-accepted-into-prestigious-artificial-intelligence-program/

Processing articles:  98%|█████████▊| 25523/26106 [1:07:24<01:16,  7.63it/s]

Updated content for https://mobileidworld.com/vietnamese-faceid-system-gets-iso-30107-3-certification/

Processing articles:  98%|█████████▊| 25526/26106 [1:07:24<01:31,  6.37it/s]

Updated content for https://www.electronicsweekly.com/news/viewpoint-image-sensing-taking-a-new-look-at-camera-sdks-iot-and-smart-cities-2024-07/
Error fetching https://www.goodreturns.in/news/digi-yatra-policy-needs-clear-data-deletion-rules-011-1354947.html: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.goodreturns.in/news/digi-yatra-policy-needs-clear-data-deletion-rules-011-1354947.html on URL https://www.goodreturns.in/news/digi-yatra-policy-needs-clear-data-deletion-rules-011-1354947.html
No content fetched for https://www.goodreturns.in/news/digi-yatra-policy-needs-clear-data-deletion-rules-011-1354947.html
Added goodreturns.in to ignored domains after 3 failures

Processing articles:  98%|█████████▊| 25528/26106 [1:07:25<01:35,  6.02it/s]

Updated content for https://www.dailypioneer.com/2024/business/digi-yatra-policy-should-spell-out-all-rules-on-passenger-info-deletion--suggests-study.html

Processing articles:  98%|█████████▊| 25535/26106 [1:07:27<02:08,  4.43it/s]

Updated content for https://thesmartlocal.com/read/david-chan-artist-singapore/

Processing articles:  98%|█████████▊| 25539/26106 [1:07:29<03:14,  2.91it/s]

Updated content for https://www.aap.com.au/aapreleases/cision20240701ae52147/

Processing articles:  98%|█████████▊| 25543/26106 [1:07:30<02:31,  3.71it/s]

Updated content for https://itc.ua/en/news/realme-13-pro-first-teaser-ai-powered-camera-and-more/

Processing articles:  98%|█████████▊| 25547/26106 [1:07:30<01:57,  4.77it/s]

Updated content for https://mises.org/power-market/does-justice-sotomayor-write-her-decisions-crayon

Processing articles:  98%|█████████▊| 25575/26106 [1:07:31<00:36, 14.41it/s]

Updated content for https://www.independent.com.mt/articles/2024-07-01/local-news/Film-Commission-and-the-Commissioner-have-to-respect-principles-of-accountability-President-6736262385

Processing articles:  98%|█████████▊| 25578/26106 [1:07:31<00:39, 13.29it/s]

Updated content for https://www.newswire.ca/news-releases/innovating-security-how-finvolution-is-taking-next-generation-technologies-to-fight-deepfake-driven-financial-crimes-872309267.html

Processing articles:  98%|█████████▊| 25595/26106 [1:07:35<01:05,  7.78it/s]

Updated content for https://flagpole.com/music/flagpole-premieres/2024/07/01/flagpole-premieres-nerveclinic-hollow-music-video/
Error fetching https://www.thenigerianvoice.com/news/337128/egbin-power-launches-innovation-hub-to-equip-future-leaders.html: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.thenigerianvoice.com/news/337128/egbin-power-launches-innovation-hub-to-equip-future-leaders.html on URL https://www.thenigerianvoice.com/news/337128/egbin-power-launches-innovation-hub-to-equip-future-leaders.html
No content fetched for https://www.thenigerianvoice.com/news/337128/egbin-power-launches-innovation-hub-to-equip-future-leaders.html

Processing articles:  98%|█████████▊| 25600/26106 [1:07:36<01:04,  7.85it/s]

Updated content for https://www.statesman.com/story/sponsor-story/thomas-henry/2024/07/01/extraordinary-women-bell-and-tyson/74235909007/
Updated content for https://www.azooptics.com/Article.aspx?ArticleID=2642

Processing articles:  98%|█████████▊| 25604/26106 [1:07:39<02:05,  3.99it/s]

Updated content for https://rki.kbs.co.kr/service/news_view.htm?lang=e&Seq_Code=186388

Processing articles:  98%|█████████▊| 25608/26106 [1:07:40<02:07,  3.91it/s]

Updated content for https://www.thecable.ng/to-ignite-creativity-genco-inaugurates-innovation-hub-for-students/

Processing articles:  98%|█████████▊| 25612/26106 [1:07:40<01:54,  4.31it/s]

Updated content for https://www.gloucestershirelive.co.uk/news/uk-world-news/jay-slater-missing-live-tenerife-9380042

Processing articles:  98%|█████████▊| 25614/26106 [1:07:41<01:48,  4.54it/s]

Error fetching https://www.stamfordadvocate.com/entertainment/article/book-review-hey-zoey-uses-questions-about-ai-19549103.php: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.stamfordadvocate.com/entertainment/article/book-review-hey-zoey-uses-questions-about-ai-19549103.php on URL https://www.stamfordadvocate.com/entertainment/article/book-review-hey-zoey-uses-questions-about-ai-19549103.php
No content fetched for https://www.stamfordadvocate.com/entertainment/article/book-review-hey-zoey-uses-questions-about-ai-19549103.php

Processing articles:  98%|█████████▊| 25616/26106 [1:07:42<02:23,  3.41it/s]

Updated content for https://celebrityaccess.com/2024/07/01/tom-kiehl-named-new-chief-executive-of-uk-music/

Processing articles:  98%|█████████▊| 25617/26106 [1:07:45<04:29,  1.82it/s]

Updated content for https://celebrityaccess.com/2024/07/01/paramount-shuts-down-mtv-news-archives-in-big-blow-to-music-industry/

Processing articles:  98%|█████████▊| 25618/26106 [1:07:46<05:20,  1.52it/s]

Updated content for https://www.interest.co.nz/technology/128523/record-labels-are-suing-tech-companies-copying-classic-songs-–-and-results-could
Error fetching https://www.thenigerianvoice.com/news/337115/gen-zs-uprising-is-not-just-east-african-kenyas-story-it.html: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.thenigerianvoice.com/news/337115/gen-zs-uprising-is-not-just-east-african-kenyas-story-it.html on URL https://www.thenigerianvoice.com/news/337115/gen-zs-uprising-is-not-just-east-african-kenyas-story-it.html
No content fetched for https://www.thenigerianvoice.com/news/337115/gen-zs-uprising-is-not-just-east-african-kenyas-story-it.html

Processing articles:  98%|█████████▊| 25635/26106 [1:07:48<01:45,  4.44it/s]

Updated content for http://www.fnbnews.com/Top-News/itcs-climate-smart-agriculture-programme-extended-to-nearly-2-lakh-women-farmers-over-10-lakh-farmers-in-total-77929

Processing articles:  98%|█████████▊| 25636/26106 [1:07:49<02:03,  3.81it/s]

Updated content for https://chestertownspy.org/2024/07/01/letter-to-editor-the-immense-impact-of-morgnec-neck-solar-field-on-chestertown-gateway/

Processing articles:  98%|█████████▊| 25642/26106 [1:07:50<01:48,  4.28it/s]

Updated content for https://www.techwyse.com/blog/digital-marketing-101/the-rise-of-voice-search-how-to-optimize-your-content-for-voice-assistants

Processing articles:  98%|█████████▊| 25652/26106 [1:07:50<01:11,  6.31it/s]

Updated content for https://www.pulse.com.gh/lifestyle/5-things-that-used-to-be-taboo-in-the-past/6qfefnv

Processing articles:  98%|█████████▊| 25657/26106 [1:07:50<00:58,  7.66it/s]

Updated content for https://www.motherjones.com/politics/2024/07/steve-bannon-prison-war-room/

Processing articles:  98%|█████████▊| 25673/26106 [1:07:52<00:43, 10.04it/s]

Updated content for https://www.africaintelligence.com/west-africa/2024/07/02/cnpc-and-petrobras-set-their-sights-on-block-4,110253572-art

Processing articles:  98%|█████████▊| 25677/26106 [1:07:52<00:41, 10.34it/s]

Error fetching https://www.kxly.com/news/laws-in-effect-today-that-idaho-residents-should-know-about/article_330733d4-37bd-11ef-acd0-e3df323f56c6.html: Article `download()` failed with 451 Client Error: Unavailable For Legal Reasons for url: https://www.kxly.com/news/laws-in-effect-today-that-idaho-residents-should-know-about/article_330733d4-37bd-11ef-acd0-e3df323f56c6.html on URL https://www.kxly.com/news/laws-in-effect-today-that-idaho-residents-should-know-about/article_330733d4-37bd-11ef-acd0-e3df323f56c6.html
No content fetched for https://www.kxly.com/news/laws-in-effect-today-that-idaho-residents-should-know-about/article_330733d4-37bd-11ef-acd0-e3df323f56c6.html

Processing articles:  98%|█████████▊| 25689/26106 [1:07:53<00:32, 12.76it/s]

Updated content for https://ifamagazine.com/what-were-the-key-themes-behind-best-and-worst-performing-us-and-uk-shares-in-h1/
Error fetching https://www.khmertimeskh.com/501515394/japanese-foreign-minister-to-pay-an-official-visit-to-cambodia/: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.khmertimeskh.com/501515394/japanese-foreign-minister-to-pay-an-official-visit-to-cambodia/ on URL https://www.khmertimeskh.com/501515394/japanese-foreign-minister-to-pay-an-official-visit-to-cambodia/
No content fetched for https://www.khmertimeskh.com/501515394/japanese-foreign-minister-to-pay-an-official-visit-to-cambodia/

Processing articles:  98%|█████████▊| 25693/26106 [1:07:54<00:50,  8.15it/s]

Updated content for https://www.aspistrategist.org.au/uns-global-digital-compact-is-looking-like-an-authoritarian-dream/

Processing articles:  98%|█████████▊| 25696/26106 [1:07:56<01:18,  5.23it/s]

Updated content for http://koreabizwire.com/hyundai-department-store-embraces-ai-for-ad-design-doubling-click-through-rates/285636

Processing articles:  98%|█████████▊| 25701/26106 [1:07:56<01:03,  6.35it/s]

Updated content for https://www.ttnews.com/articles/chamber-amicus-brief-werner

Processing articles:  99%|█████████▊| 25717/26106 [1:07:58<00:54,  7.11it/s]

Updated content for https://www.narrativa.com/ensuring-patients-privacy-data-sensitivity-in-pharma/

Processing articles:  99%|█████████▊| 25719/26106 [1:07:59<01:02,  6.24it/s]

Updated content for https://www.supermarketnews.com/news/amazon-gets-fresh-start-brick-and-mortar-grocery

Processing articles:  99%|█████████▊| 25723/26106 [1:07:59<01:02,  6.17it/s]

Updated content for https://www.cryptonewsz.com/us-marshals-service-for-coinbase-digital-asset/

Processing articles:  99%|█████████▊| 25743/26106 [1:08:01<00:35, 10.14it/s]

Updated content for https://infotel.ca/newsitem/ent-book-review-hey/cp957480076
Error fetching https://www.udayavani.com/english-news/karnataka-govt-opposes-new-criminal-laws-says-centre-did-not-take-suggestions: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.udayavani.com/english-news/karnataka-govt-opposes-new-criminal-laws-says-centre-did-not-take-suggestions on URL https://www.udayavani.com/english-news/karnataka-govt-opposes-new-criminal-laws-says-centre-did-not-take-suggestions
No content fetched for https://www.udayavani.com/english-news/karnataka-govt-opposes-new-criminal-laws-says-centre-did-not-take-suggestions

Processing articles:  99%|█████████▊| 25759/26106 [1:08:07<01:13,  4.70it/s]

Updated content for https://www.bbs.bt/news/?p=205743

Processing articles:  99%|█████████▊| 25765/26106 [1:08:07<01:03,  5.34it/s]

Updated content for https://www.businessreport.com/article/gov-landry-vetoes-bill-banning-deepfakes-in-louisiana-heres-why

Processing articles:  99%|█████████▊| 25770/26106 [1:08:08<01:01,  5.49it/s]

Updated content for https://www.naijanews.com/2024/07/02/nigeria-security-operatives-enjoy-carte-blanche-no-accountability-ai/

Processing articles:  99%|█████████▊| 25773/26106 [1:08:09<01:07,  4.93it/s]

Updated content for https://www.diabetes.co.uk/news/2024/jul/patient-details-published-following-cyber-attack-on-london-hospitals.html

Processing articles:  99%|█████████▊| 25777/26106 [1:08:11<01:16,  4.32it/s]

Updated content for https://www.insuranceinsider.com/article/2dft9mizp6qvduwuqns3k/brokers-section/cyber-pricing-drops-15-from-2022-peak-howden

Processing articles:  99%|█████████▊| 25779/26106 [1:08:12<01:35,  3.44it/s]

Updated content for https://www.royalgazette.com/reinsurance/business/article/20240701/more-cyber-growth-expected-in-non-us-insurance/

Processing articles:  99%|█████████▉| 25782/26106 [1:08:14<01:53,  2.86it/s]

Updated content for https://www.escapistmagazine.com/jailbreak-codes/

Processing articles:  99%|█████████▉| 25785/26106 [1:08:15<01:49,  2.92it/s]

Updated content for https://www.bssnews.net/sports/197849

Processing articles:  99%|█████████▉| 25788/26106 [1:08:18<02:54,  1.82it/s]

Updated content for https://www.bssnews.net/international/197851

Processing articles:  99%|█████████▉| 25790/26106 [1:08:20<03:07,  1.69it/s]

Updated content for https://www.gamepur.com/guides/jailbreak-codes-roblox

Processing articles:  99%|█████████▉| 25792/26106 [1:08:21<02:53,  1.81it/s]

Updated content for https://www.bssnews.net/sports/197854
Updated content for https://www.channel4.com/news/exclusive-top-uk-politicians-victims-of-deepfake-pornography

Processing articles:  99%|█████████▉| 25798/26106 [1:08:22<01:48,  2.85it/s]

Updated content for https://www.semiconductorpackagingnews.com/news/86438.html

Processing articles:  99%|█████████▉| 25799/26106 [1:08:29<05:50,  1.14s/it]

Error fetching https://www.timesnownews.com/technology-science/this-viral-ai-chatbot-lies-and-mimics-human-voices-researchers-warn-article-111416690: Article `download()` failed with HTTPSConnectionPool(host='www.timesnownews.com', port=443): Read timed out. (read timeout=7) on URL https://www.timesnownews.com/technology-science/this-viral-ai-chatbot-lies-and-mimics-human-voices-researchers-warn-article-111416690
No content fetched for https://www.timesnownews.com/technology-science/this-viral-ai-chatbot-lies-and-mimics-human-voices-researchers-warn-article-111416690

Processing articles:  99%|█████████▉| 25801/26106 [1:08:30<05:23,  1.06s/it]

Updated content for https://www.margaretrivermail.com.au/story/8680497/ai-and-deepfakes-what-the-future-of-human-interaction-looks-like/

Processing articles:  99%|█████████▉| 25802/26106 [1:08:33<06:17,  1.24s/it]

Updated content for https://herald-zeitung.com/opinion/roberts-the-startling-flood-of-disinformation/article_d12f7d42-37c6-11ef-8ebb-ebbf0040bce2.html

Processing articles:  99%|█████████▉| 25811/26106 [1:08:33<02:14,  2.19it/s]

Updated content for https://www.cnbcafrica.com/2024/smartphone-companies-using-ai-to-detect-deepfakes/

Processing articles:  99%|█████████▉| 25818/26106 [1:08:35<01:51,  2.58it/s]

Updated content for https://talksport.com/football/1889122/euro-2024-live-england-france-belgium-portugal-ronaldo-news-results/page/6/

Processing articles:  99%|█████████▉| 25819/26106 [1:08:36<01:55,  2.48it/s]

Error fetching https://www.albianews.com/news/state/article_9f3d4b23-11a6-53d9-a709-19b8fd2715ef.html: Article `download()` failed with 451 Client Error: Unavailable For Legal Reasons for url: https://www.albianews.com/news/state/article_9f3d4b23-11a6-53d9-a709-19b8fd2715ef.html on URL https://www.albianews.com/news/state/article_9f3d4b23-11a6-53d9-a709-19b8fd2715ef.html
No content fetched for https://www.albianews.com/news/state/article_9f3d4b23-11a6-53d9-a709-19b8fd2715ef.html

Processing articles:  99%|█████████▉| 25820/26106 [1:08:39<03:02,  1.57it/s]

Updated content for https://www.aap.com.au/aapreleases/cision20240701ae52300/

Processing articles:  99%|█████████▉| 25821/26106 [1:08:40<03:19,  1.43it/s]

Updated content for https://shots.net/the-future-focus-24

Processing articles:  99%|█████████▉| 25828/26106 [1:08:41<01:49,  2.55it/s]

Updated content for https://www.keranews.org/texas-news/2024-07-01/how-dirty-are-texas-beaches-researchers-are-using-ai-to-better-track-bacteria-levels
Error fetching https://www.philanthropy.com/article/nvidia-executive-gives-20-million-to-fight-cancer-with-a-i-tools: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.philanthropy.com/article/nvidia-executive-gives-20-million-to-fight-cancer-with-a-i-tools on URL https://www.philanthropy.com/article/nvidia-executive-gives-20-million-to-fight-cancer-with-a-i-tools
No content fetched for https://www.philanthropy.com/article/nvidia-executive-gives-20-million-to-fight-cancer-with-a-i-tools

Processing articles:  99%|█████████▉| 25829/26106 [1:08:42<02:20,  1.98it/s]

Updated content for https://recyclinginternational.com/commodities/plastics-recycling/stadler-ahead-of-the-curb-with-wirex-and-digital-vision/57681/

Processing articles:  99%|█████████▉| 25831/26106 [1:08:45<03:36,  1.27it/s]

Updated content for https://www.yourlifechoices.com.au/health/smartphone-screening-tool-could-help-detect-strokes-faster/

Processing articles:  99%|█████████▉| 25833/26106 [1:08:46<02:49,  1.61it/s]

Updated content for https://businesstech.co.za/news/industry-news/780358/using-artificial-intelligence-to-drive-positive-societal-change/

Processing articles:  99%|█████████▉| 25835/26106 [1:08:46<02:26,  1.84it/s]

Updated content for https://www.ktnv.com/news/rtc-begins-their-deployment-of-300-armed-security-officers-across-the-valley

Processing articles:  99%|█████████▉| 25839/26106 [1:08:50<02:58,  1.49it/s]

Updated content for https://communitynewspapers.com/inspire-health/the-mri-scanner-yesterday-and-today/

Processing articles:  99%|█████████▉| 25840/26106 [1:08:51<03:12,  1.38it/s]

Updated content for https://www.hstoday.us/subject-matter-areas/counterterrorism/right-wing-extremism-in-military-on-the-rise/

Processing articles:  99%|█████████▉| 25842/26106 [1:08:52<03:12,  1.37it/s]

Updated content for https://www.electronicsforu.com/press-releases/early-access-to-mplab-extensions-for-vs-code-provides-designers-with-the-ability-to-utilize-microchips-development-tools-inside-of-the-popular-ide

Processing articles:  99%|█████████▉| 25845/26106 [1:08:53<02:17,  1.90it/s]

Error fetching https://www.elpasoinc.com/news/state/man-charged-with-possession-of-child-pornography-after-allegedly-using-artificial-intelligence/article_cdffe797-ac46-5e41-b47a-0cac1e64f01e.html: Article `download()` failed with 451 Client Error: Unavailable For Legal Reasons for url: https://www.elpasoinc.com/news/state/man-charged-with-possession-of-child-pornography-after-allegedly-using-artificial-intelligence/article_cdffe797-ac46-5e41-b47a-0cac1e64f01e.html on URL https://www.elpasoinc.com/news/state/man-charged-with-possession-of-child-pornography-after-allegedly-using-artificial-intelligence/article_cdffe797-ac46-5e41-b47a-0cac1e64f01e.html
No content fetched for https://www.elpasoinc.com/news/state/man-charged-with-possession-of-child-pornography-after-allegedly-using-artificial-intelligence/article_cdffe797-ac46-5e41-b47a-0cac1e64f01e.html

Processing articles:  99%|█████████▉| 25846/26106 [1:08:53<02:14,  1.93it/s]

Updated content for https://talkbusiness.net/2024/07/veteran-entrepreneur-accelerator-program-lands-in-bentonville/

Processing articles:  99%|█████████▉| 25852/26106 [1:08:54<01:06,  3.80it/s]

Updated content for https://www.corriere.it/tecnologia/cards/le-migliori-piattaforme-di-intelligenza-artificiale-guida-completa-a-chatgpt-gemini-claude-meta-ai-e-gli-altri/chatgpt-open-ai-le-caratteristiche.shtml

Processing articles:  99%|█████████▉| 25857/26106 [1:08:54<00:46,  5.32it/s]

Updated content for https://www.napolike.it/la-promessa-spoiler-dalla-spagna-pia-inscena-la-sua-morte

Processing articles:  99%|█████████▉| 25859/26106 [1:08:54<00:45,  5.38it/s]

Updated content for https://www.affaritaliani.it/cronache/napoli-boss-minacce-alla-compagna-se-ti-metti-con-un-altro-ti-ammazzo-926185.html

Processing articles:  99%|█████████▉| 25860/26106 [1:08:55<00:53,  4.62it/s]

Updated content for https://www.wired.it/article/intelligenza-artificiale-open-source-blockchain-illia-polosukhin/

Processing articles:  99%|█████████▉| 25862/26106 [1:08:55<00:57,  4.26it/s]

Updated content for https://www.ilgiornale.it/news/cronaca-giudiziaria/caso-uss-confermato-larresto-complice-dimitry-chirakadze-2341559.html

Processing articles:  99%|█████████▉| 25864/26106 [1:08:56<00:57,  4.18it/s]

Updated content for https://tech.everyeye.it/notizie/intelligenza-artificiale-sa-davvero-ragionare-risposta-sorprendervi-726991.html

Processing articles:  99%|█████████▉| 25866/26106 [1:08:56<00:57,  4.20it/s]

Updated content for https://www.vanityfair.it/article/silvia-salemi-intervista-malattia-sorella-musica
Error fetching https://www.tag24.it/1142713-maltempo-piemonte-valle-daosta-1-luglio-2024-diretta/: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.tag24.it/1142713-maltempo-piemonte-valle-daosta-1-luglio-2024-diretta/ on URL https://www.tag24.it/1142713-maltempo-piemonte-valle-daosta-1-luglio-2024-diretta/
No content fetched for https://www.tag24.it/1142713-maltempo-piemonte-valle-daosta-1-luglio-2024-diretta/

Processing articles:  99%|█████████▉| 25867/26106 [1:08:57<00:55,  4.29it/s]

Updated content for https://www.editorialedomani.it/politica/italia/the-hollywood-reporter-roma-dimissioni-giornalisti-cosa-e-successo-comunicato-redazione-editore-wb2yhpkr

Processing articles:  99%|█████████▉| 25870/26106 [1:08:57<00:47,  4.94it/s]

Updated content for https://www.ilsussidiario.net/news/crisi-m5s-grillo-verso-amnistia-agli-espulsi-5stelle-da-lezzi-a-morra-gli-scenari-conte-commissariato/2725317/

Processing articles:  99%|█████████▉| 25871/26106 [1:08:57<00:55,  4.26it/s]

Updated content for https://www.altovicentinonline.it/storie-e-realta-territoriali/tragedia-della-marmolada-due-anni-dopo-il-clima-non-fa-sconti/

Processing articles:  99%|█████████▉| 25874/26106 [1:08:58<00:56,  4.07it/s]

Updated content for https://aviationweek.com/air-transport/airlines-lessors/airasia-x-adding-new-flights-kuala-lumpur-africa

Processing articles:  99%|█████████▉| 25878/26106 [1:09:01<01:44,  2.17it/s]

Updated content for https://www.traveltrendstoday.in/air-india-to-establish-south-asias-largest-flying-training-academy-in-amravati-maharashtra/

Processing articles:  99%|█████████▉| 25880/26106 [1:09:02<01:46,  2.12it/s]

Updated content for https://www.stripes.com/branches/air_force/2024-07-01/air-force-boeing-air-refueling-wing-kc-46a-circumnavigation-14357687.html

Processing articles:  99%|█████████▉| 25883/26106 [1:09:03<01:20,  2.76it/s]

Updated content for https://www.aircargonews.net/airlines/silk-way-signs-air-cargo-mou-with-china-henan-aviation/

Processing articles:  99%|█████████▉| 25886/26106 [1:09:04<01:39,  2.20it/s]

Updated content for https://english.vov.vn/en/economy/vietnamese-business-honoured-at-2024-asia-excellent-brand-awards-post1105058.vov

Processing articles:  99%|█████████▉| 25888/26106 [1:09:07<02:09,  1.68it/s]

Updated content for https://asianaviation.com/air-astana-boosting-flights-to-china/

Processing articles:  99%|█████████▉| 25889/26106 [1:09:07<02:04,  1.74it/s]

Updated content for https://www.dailysignal.com/2024/07/01/chinas-maritime-gamble-departure-gray-zone-coercion-east-asia/

Processing articles:  99%|█████████▉| 25906/26106 [1:09:09<00:45,  4.35it/s]

Updated content for https://english.vov.vn/en/politics/diplomacy/vietnam-and-rok-to-boost-labour-cooperation-post1105064.vov

Processing articles:  99%|█████████▉| 25908/26106 [1:09:10<00:47,  4.20it/s]

Updated content for https://crypto2community.com/crypto-news/tether-enables-usdt-payments-for-philippine-social-security/

Processing articles:  99%|█████████▉| 25914/26106 [1:09:11<00:38,  5.05it/s]

Updated content for https://www.masslive.com/news/2024/07/mass-general-brigham-fires-employees-after-patient-privacy-breach.html

Processing articles:  99%|█████████▉| 25922/26106 [1:09:11<00:28,  6.54it/s]

Updated content for https://www.bitdefender.com/blog/hotforsecurity/how-to-avoid-scams-when-shopping-for-bargains-online/

Processing articles:  99%|█████████▉| 25937/26106 [1:09:12<00:16, 10.05it/s]

Updated content for https://comicbookmovie.com/avengers/avengers-secret-wars/5-ways-iron-man-star-robert-downey-jr-can-return-to-the-marvel-cinematic-universe-a211756

Processing articles:  99%|█████████▉| 25943/26106 [1:09:13<00:18,  8.94it/s]

Updated content for https://www.djfood.org/tag/record-shop-stories/

Processing articles:  99%|█████████▉| 25945/26106 [1:09:14<00:25,  6.21it/s]

Updated content for https://www.winnipegfreepress.com/arts-and-life/entertainment/books/2024/07/01/book-review-hey-zoey-uses-questions-about-ai-to-look-at-womens-autonomy-in-a-new-light

Processing articles:  99%|█████████▉| 25955/26106 [1:09:16<00:23,  6.41it/s]

Updated content for https://www.therolladailynews.com/3-best-ai-tools-for-business/

Processing articles:  99%|█████████▉| 25956/26106 [1:09:16<00:26,  5.75it/s]

Updated content for https://grmdaily.com/ai-prison-rewires-brain/

Processing articles:  99%|█████████▉| 25957/26106 [1:09:17<00:29,  5.03it/s]

Updated content for https://www.mrweb.com/drno/news36903.htm

Processing articles:  99%|█████████▉| 25961/26106 [1:09:17<00:28,  5.01it/s]

Updated content for https://www.oneesports.gg/anime/how-many-episodes-are-in-oshi-no-ko-season-2/

Processing articles:  99%|█████████▉| 25962/26106 [1:09:19<00:53,  2.71it/s]

Updated content for https://www.shine.cn/news/nation/2407014001/

Processing articles:  99%|█████████▉| 25963/26106 [1:09:20<00:56,  2.51it/s]

Updated content for https://www.avclub.com/steven-soderbergh-talks-taylor-swift-fascinated-1851571199

Processing articles:  99%|█████████▉| 25967/26106 [1:09:21<00:48,  2.84it/s]

Updated content for https://www.indiablooms.com/showbiz-details/B/18682/the-balance-between-technology-and-real-performances-made-kalki-2898-ad-very-special-deepika-padukone.html

Processing articles:  99%|█████████▉| 25973/26106 [1:09:21<00:28,  4.67it/s]

Updated content for https://www.aspentimes.com/news/from-darkroom-secrets-to-enlightening-art-liz-nielsens-solo-show-at-hexton/

Processing articles:  99%|█████████▉| 25974/26106 [1:09:23<00:42,  3.14it/s]

Updated content for https://knowridge.com/2024/07/nbc-using-ai-to-clone-al-michaels-voice-for-the-olympics-experts-says-theres-room-for-human-and-ai-generated-voices/

Processing articles:  99%|█████████▉| 25975/26106 [1:09:23<00:45,  2.86it/s]

Updated content for https://www.iberkshires.com/story/75834/Clark-Art-Concert-by-Jacques-Schwarz-Bart.html

Processing articles: 100%|█████████▉| 25987/26106 [1:09:25<00:18,  6.41it/s]

Updated content for https://iafrica.com/landscape-analysis-of-ai-startups-in-africa/
Error fetching https://www.fa-mag.com/news/goldman-says-earnings-bar-is-set-highest-since-2021-78644.html: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.fa-mag.com/news/goldman-says-earnings-bar-is-set-highest-since-2021-78644.html on URL https://www.fa-mag.com/news/goldman-says-earnings-bar-is-set-highest-since-2021-78644.html
No content fetched for https://www.fa-mag.com/news/goldman-says-earnings-bar-is-set-highest-since-2021-78644.html
Added fa-mag.com to ignored domains after 3 failures

Processing articles: 100%|█████████▉| 25992/26106 [1:09:25<00:14,  8.12it/s]

Updated content for https://www.pharmiweb.com/press-release/2024-07-02/global-veterinary-infectious-disease-diagnostics-market-projected-to-surpass-usd-49-billion-by-2033

Processing articles: 100%|█████████▉| 26009/26106 [1:09:25<00:06, 15.79it/s]

Error fetching https://www.bozemandailychronicle.com/ap_news/conversation/chatgpt-and-the-movie-her-are-just-the-latest-example-of-the-sci-fi-feedback/article_8278bb9e-ceda-5975-9423-5ccf26633e4c.html: Article `download()` failed with 451 Client Error: Unavailable For Legal Reasons for url: https://www.bozemandailychronicle.com/ap_news/conversation/chatgpt-and-the-movie-her-are-just-the-latest-example-of-the-sci-fi-feedback/article_8278bb9e-ceda-5975-9423-5ccf26633e4c.html on URL https://www.bozemandailychronicle.com/ap_news/conversation/chatgpt-and-the-movie-her-are-just-the-latest-example-of-the-sci-fi-feedback/article_8278bb9e-ceda-5975-9423-5ccf26633e4c.html
No content fetched for https://www.bozemandailychronicle.com/ap_news/conversation/chatgpt-and-the-movie-her-are-just-the-latest-example-of-the-sci-fi-feedback/article_8278bb9e-ceda-5975-9423-5ccf26633e4c.html
Added bozemandailychronicle.com to ignored domains after 3 failures

Processing articles: 100%|█████████▉| 26023/26106 [1:09:26<00:04, 19.03it/s]

Updated content for https://www.skysports.com/f1/news/12040/13161951/max-verstappen-will-be-treated-fairly-by-fans-at-silverstone-says-british-gp-boss-stuart-pringle
Updated content for https://www.espn.com/nrl/story/_/id/40470298/nrl-round-18-teams-line-ups-tips-odds-everything-need-know-weekend

Processing articles: 100%|█████████▉| 26026/26106 [1:09:27<00:07, 10.37it/s]

Updated content for https://www.inverness-courier.co.uk/sport/inverness-four-day-open-swings-into-action-as-first-round-be-354450/

Processing articles: 100%|█████████▉| 26029/26106 [1:09:28<00:08,  8.76it/s]

Updated content for https://www.dailyrecord.co.uk/sport/football/football-transfer-news/transfer-news-live-celtic-rangers-33140204

Processing articles: 100%|█████████▉| 26031/26106 [1:09:29<00:11,  6.30it/s]

Updated content for https://www.dailyecho.co.uk/sport/24422351.southampton-want-oriley-personal-terms-need-resolving/

Processing articles: 100%|█████████▉| 26033/26106 [1:09:32<00:24,  2.95it/s]

Updated content for https://www.dailyecho.co.uk/sport/24421285.latest-southampton-transfer-rumours-including-oriley-clarke/

Processing articles: 100%|█████████▉| 26034/26106 [1:09:32<00:24,  2.89it/s]

Updated content for https://www.espn.com/f1/story/_/id/40471981/max-verstappen-deserve-penalty-says-christian-horner

Processing articles: 100%|█████████▉| 26041/26106 [1:09:33<00:14,  4.60it/s]

Updated content for https://www.motorsportmagazine.com/articles/single-seaters/f1/last-minute-surge-in-2024-british-gp-ticket-sales-after-lando-and-max-f1-battle/

Processing articles: 100%|█████████▉| 26047/26106 [1:09:34<00:11,  5.14it/s]

Updated content for https://ew.com/best-disney-channel-original-movies-ranked-8672062

Processing articles: 100%|█████████▉| 26053/26106 [1:09:35<00:10,  5.15it/s]

Error fetching https://nz.finance.yahoo.com/quote/M44.BE/chart/: Article `download()` failed with 503 Server Error: Service Unavailable for url: https://nz.finance.yahoo.com/quote/M44.BE/chart/ on URL https://nz.finance.yahoo.com/quote/M44.BE/chart/
No content fetched for https://nz.finance.yahoo.com/quote/M44.BE/chart/

Processing articles: 100%|█████████▉| 26057/26106 [1:09:35<00:08,  5.49it/s]

Updated content for https://www.timeout.com/newyork/news/seven-weeks-of-free-live-performances-are-set-for-nycs-little-island-070124

Processing articles: 100%|█████████▉| 26060/26106 [1:09:37<00:10,  4.45it/s]

Updated content for https://www.semiconductorpackagingnews.com/news/86446.html

Processing articles: 100%|█████████▉| 26064/26106 [1:09:37<00:08,  4.67it/s]

Updated content for https://bankerandtradesman.com/houses-economic-development-bill-includes-cre-investments/
Error fetching https://www.khmertimeskh.com/501515554/asian-stocks-gains-as-economic-data-mixed-for-japan-china/: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.khmertimeskh.com/501515554/asian-stocks-gains-as-economic-data-mixed-for-japan-china/ on URL https://www.khmertimeskh.com/501515554/asian-stocks-gains-as-economic-data-mixed-for-japan-china/
No content fetched for https://www.khmertimeskh.com/501515554/asian-stocks-gains-as-economic-data-mixed-for-japan-china/
Added khmertimeskh.com to ignored domains after 3 failures

Processing articles: 100%|█████████▉| 26067/26106 [1:09:39<00:10,  3.77it/s]

Updated content for https://foreignpolicy.com/podcasts/the-geopolitics-of-business/

Processing articles: 100%|█████████▉| 26068/26106 [1:09:41<00:18,  2.09it/s]

Updated content for https://foreignpolicy.com/projects/2023-foreign-policy-year-in-review/

Processing articles: 100%|█████████▉| 26072/26106 [1:09:41<00:11,  2.94it/s]

Updated content for https://www.vanityfair.com/news/story/louise-blouin-bankrupt-interview

Processing articles: 100%|█████████▉| 26073/26106 [1:09:42<00:13,  2.53it/s]

Updated content for https://en.trend.az/business/energy/3918435.html

Processing articles: 100%|█████████▉| 26083/26106 [1:09:44<00:05,  4.12it/s]

Updated content for https://www.ft.lk/opinion/Current-status-of-construction-contractors-in-time-of-crisis-and-implications-on-economy/14-763719

Processing articles: 100%|█████████▉| 26084/26106 [1:09:45<00:08,  2.74it/s]

Updated content for https://www.dailymaverick.co.za/article/2024-07-01-the-tragedy-of-political-leaders-and-advancing-age/

Processing articles: 100%|█████████▉| 26085/26106 [1:09:46<00:08,  2.49it/s]

Updated content for https://artreview.com/the-top-10-exhibitions-to-see-in-july-2024/

Processing articles: 100%|█████████▉| 26089/26106 [1:09:47<00:05,  3.35it/s]

Updated content for https://www.examenglish.com/FCE/fce_use_of_english_part2.htm

Processing articles: 100%|██████████| 26106/26106 [1:09:47<00:00,  6.23it/s]

Updated content for https://www.sportspromedia.com/news/the-open-ntt-data-tech-5g-digital-twin/
Updated 2890 articles, skipped 23216 articles
Total processed: 3512
Newly ignored domains: {'charlotteobserver.com', 'standard-journal.com', 'weeklytimesnow.com.au', 'therepublic.com', 'autonews.com', 'kfor.com', 'sinchew.com.my', 'bozemandailychronicle.com', 'agoramagazine.it', 'business-reporter.co.uk', 'qmul.ac.uk', 'caledonianrecord.com', 'simpleflying.com', 'thelancet.com', 'triblive.com', 'chron.com', 'thegrio.com', 'macaubusiness.com', 'in.investing.com', 'greekreporter.com', 'realclearscience.com', 'sbr.com.sg', 'extremetech.com', 'kdvr.com', 'chronicle.com', 'kpvi.com', 'yorkshirepost.co.uk', 'purdueexponent.org', 'insidermedia.com', 'ijr.com', 'kcci.com', 'marketindex.com.au', 'moneymorning.com', 'blogs.timesofisrael.com', 'scotsman.com', 'startupdaily.net', 'agi.it', 'news-journal.com', 'citizen.co.za', 'iol.co.za', 'sfweekly.com', 'lse.co.uk', 'english.ahram.org.eg', 'khou.com', 'freemalaysiatoday.com', 'thedailystar.com', 'houstonchronicle.com', 'headtopics.com', 'netindia123.com', 'chicagobusiness.com', 'modernhealthcare.com', 'en.qdnd.vn', 'graphic.com.gh', 'goodreturns.in', 'insights.globalspec.com', 'crainsnewyork.com', 'propakistani.pk', 'wreg.com', 'healthaffairs.org', 'thenationonlineng.net', 'moneyweb.co.za', 'ibj.com', 'wyomingnews.com', 'kansascity.com', 'heraldsun.com.au', 'pastemagazine.com', 'vietnamnet.vn', 'c-span.org', 'ktla.com', 'khmertimeskh.com', 'engineeringnews.co.za', 'jang.com.pk', 'leadership.ng', 'augustman.com', 'alkhaleejtoday.co', 'courant.com', 'vanguardngr.com', 'thechronicle.com.au', 'seattlepi.com', 'iwradio.co.uk', 'adelaidenow.com.au', 'forexfactory.com', 'newsobserver.com', 'fa-mag.com', 'fiercebiotech.com'}

### Export updated df

In [55]:
from datetime import datetime
from os.path import join

output = join("data", f"blogdb.ai_news_{datetime.now().strftime('%Y_%m_%d_%H_%M')}.csv")

df.to_csv(output, index=False, encoding="utf-8")

# Update mongoDB with the page_content